// 格式转换器：base64 / Clash YAML / Sing-box JSON / Quantumult X
import { parseNode } from './parsers.js';

function esc(s) {
  return String(s == null ? '' : s).replace(/[\\"]/g, c => '\\' + c);
}

function yamlList(items, indent = 6) {
  const pad = ' '.repeat(indent);
  return (items.length ? items : ['DIRECT']).map(n => `${pad}- "${n}"`).join('\n');
}

export function toBase64(nodes) {
  const text = nodes.map(n => n.uri).filter(Boolean).join('\n');
  const bytes = new TextEncoder().encode(text);
  let bin = '';
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}

export function toClash(nodes) {
  const proxies = [];
  const names = [];
  for (const n of nodes) {
    const p = parseNode(n);
    if (!p) continue;
    const name = esc(p.name);
    let line = '';
    switch (p.type) {
      case 'vmess':
        line = `  - { name: "${name}", type: vmess, server: ${p.server}, port: ${p.port}, uuid: "${p.uuid}", alterId: ${p.alterId}, cipher: ${p.cipher}, udp: true`;
        if (p.tls) line += `, tls: true, servername: "${p.sni}"`;
        if (p.network === 'ws') line += `, network: ws, ws-opts: { path: "${p.wsPath}", headers: { Host: "${p.wsHost}" } }`;
        line += ' }';
        break;
      case 'vless':
        line = `  - { name: "${name}", type: vless, server: ${p.server}, port: ${p.port}, uuid: "${p.uuid}", udp: true, packet-encoding: xudp`;
        if (p.flow) line += `, flow: ${p.flow}`;
        if (p.security === 'reality') {
          line += `, tls: true, servername: "${p.sni}", client-fingerprint: ${p.fp || 'chrome'}, reality-opts: { public-key: "${p.realityPbk}", short-id: "${p.realitySid}" }`;
        } else if (p.security === 'tls') {
          line += `, tls: true, servername: "${p.sni}"`;
        }
        if (p.network === 'ws') line += `, network: ws, ws-opts: { path: "${p.wsPath}", headers: { Host: "${p.wsHost}" } }`;
        line += ' }';
        break;
      case 'trojan':
        line = `  - { name: "${name}", type: trojan, server: ${p.server}, port: ${p.port}, password: "${esc(p.password)}", udp: true`;
        if (p.sni) line += `, sni: "${p.sni}"`;
        if (p.allowInsecure) line += `, skip-cert-verify: true`;
        if (p.network === 'ws') line += `, network: ws, ws-opts: { path: "${p.wsPath}" }`;
        line += ' }';
        break;
      case 'ss':
        line = `  - { name: "${name}", type: ss, server: ${p.server}, port: ${p.port}, cipher: ${p.method}, password: "${esc(p.password)}", udp: true }`;
        break;
      case 'hysteria':
        line = `  - { name: "${name}", type: hysteria, server: ${p.server}, port: ${p.port}, auth_str: "${esc(p.password)}"`;
        if (p.sni) line += `, sni: "${p.sni}"`;
        if (p.obfs) line += `, obfs: ${p.obfs}`;
        if (p.insecure) line += `, skip-cert-verify: true`;
        line += ' }';
        break;
      case 'hy2':
        line = `  - { name: "${name}", type: hysteria2, server: ${p.server}, port: ${p.port}, password: "${esc(p.password)}"`;
        if (p.sni) line += `, sni: "${p.sni}"`;
        if (p.obfs) line += `, obfs: { type: ${p.obfs} }`;
        if (p.insecure) line += `, skip-cert-verify: true`;
        line += ' }';
        break;
    }
    if (line) { proxies.push(line); names.push(name); }
  }
  const all = yamlList(names);
  return `# Auto-generated by v2ray-sub
mixed-port: 7890
allow-lan: false
mode: rule
log-level: warning
proxies:
${proxies.join('\n')}
proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
${all}
  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
${all}
rules:
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
`;
}

export function toSingbox(nodes) {
  const outbounds = [];
  for (const n of nodes) {
    const p = parseNode(n);
    if (!p) continue;
    const ob = { tag: p.name, type: p.type };
    switch (p.type) {
      case 'vmess':
        Object.assign(ob, {
          server: p.server, server_port: p.port, uuid: p.uuid,
          security: p.tls ? 'tls' : 'none', alter_id: p.alterId,
        });
        if (p.network === 'ws') ob.transport = { type: 'ws', path: p.wsPath, headers: { Host: p.wsHost } };
        if (p.tls) ob.tls = { enabled: true, server_name: p.sni };
        break;
      case 'vless':
        Object.assign(ob, {
          server: p.server, server_port: p.port, uuid: p.uuid,
          flow: p.flow || undefined, packet_encoding: 'xudp',
        });
        if (p.security === 'tls') ob.tls = { enabled: true, server_name: p.sni };
        if (p.security === 'reality') {
          ob.tls = {
            enabled: true, server_name: p.sni,
            utls: { enabled: true, fingerprint: p.fp || 'chrome' },
            reality: { public_key: p.realityPbk, short_id: p.realitySid },
          };
        }
        if (p.network === 'ws') ob.transport = { type: 'ws', path: p.wsPath, headers: { Host: p.wsHost } };
        break;
      case 'trojan':
        Object.assign(ob, {
          server: p.server, server_port: p.port, password: p.password,
        });
        if (p.sni) ob.tls = { enabled: true, server_name: p.sni };
        break;
      case 'ss':
        Object.assign(ob, { server: p.server, server_port: p.port, method: p.method, password: p.password });
        break;
      case 'hysteria':
        ob.type = 'hysteria';
        Object.assign(ob, { server: p.server, server_port: p.port, auth_str: p.password });
        if (p.sni) ob.tls = { enabled: true, server_name: p.sni };
        if (p.obfs) ob.obfs = { type: p.obfs };
        break;
      case 'hy2':
        ob.type = 'hysteria2';
        Object.assign(ob, { server: p.server, server_port: p.port, password: p.password });
        if (p.sni) ob.tls = { enabled: true, server_name: p.sni };
        if (p.obfs) ob.obfs = { type: p.obfs };
        break;
    }
    outbounds.push(ob);
  }
  return JSON.stringify({
    log: { level: 'info' },
    inbounds: [
      { type: 'mixed', tag: 'mixed-in', listen: '127.0.0.1', listen_port: 2080 },
    ],
    outbounds: [
      { type: 'selector', tag: 'proxy', outbounds: outbounds.map(o => o.tag).concat(['direct']) },
      { type: 'direct', tag: 'direct' },
    ].concat(outbounds),
    route: { final: 'proxy', auto_detect_interface: true },
  }, null, 2);
}

export function toQuantumult(nodes) {
  const lines = [];
  for (const n of nodes) {
    const p = parseNode(n);
    if (!p) continue;
    let line = null;
    switch (p.type) {
      case 'vmess':
        line = `vmess=${p.server}:${p.port}, method=chacha20-poly1305, password=${p.uuid}, obfs=wss, obfs-uri=/, obfs-host=${p.sni}, tag=${p.name}`;
        break;
      case 'vless':
        line = `vless=${p.server}:${p.port}, password=${p.uuid}, obfs=wss, obfs-uri=/, obfs-host=${p.sni}, tag=${p.name}`;
        break;
      case 'trojan':
        line = `trojan=${p.server}:${p.port}, password=${p.password}, obfs=wss, obfs-uri=/, obfs-host=${p.sni}, tag=${p.name}`;
        break;
      case 'ss':
        line = `shadowsocks=${p.server}:${p.port}, method=${p.method}, password=${p.password}, tag=${p.name}`;
        break;
    }
    if (line) lines.push(line);
  }
  return lines.join('\n');
}
